language: php
sudo: false

php:
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ] || [ $TRAVIS_PHP_VERSION = '7.3' ]; then composer self-update --1 --no-progress --no-interaction; fi
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --diff --dry-run --using-cache=no; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.4' ]; then php vendor/bin/php-coveralls -v -x build/clover.xml -o build/clover.json; fi

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "i7A8KIe+CHVssWU79LYNZxzN40PLGmdqiFSEiPwsbWz/WdWWq6FNNmhrqbBM3gExpKRHYuZCgrW4rCNJZ4FVht0sFkMfj7vT7RW6HlX9dNDdd3xNxzAIss4CNhaAc+h1fsNZB+2A8oniYreQFugbEJHruEQzibjxRg0u7bWFyzqkTGjxsrQQCyLIH2NO83HOioPSsCpdDl8wNBs/F2vM1Lphz3tJQky2OEHoCUS09r9oLKTKZOGUsINDbV+pZj8Lf3zEzaJ4CIdYqA/vqC+MI+HIYXeoYdytj3KHbuLCo6x2MH8Zg8x4ypJfCJs5YZ2wAyh0aJaXkIVdh1RA0Tcp/Ya3p3tk7irWsvb+fUKF4lDlyZ20iUlyaOSoLgivnyqkhE3qL3jS26EUYl5jzm+SWUC8OJIFVIH0coipuz+g583ZvS8eiOTc/ObM/Ake9TEc+hGoNNQfR9XJ93raS18pXbLxgve1CM6I3G81ULqcohWdyc9lrUSgZy8GJUTEf+/vlnxUMze5YlnE1j9BQa6FT+AAhLj+kuilLcfIyPkE7vzp8O9pWyUYh/CKMoEA1mnuo+vRIXv7UKakjCJEklRrsmFI7ZzItCCEvtvaU4EMExfO1oyIie51qWbIWbwvtGeTaRYcq5TrABO8Puu46sJPjgwDdCDfZWEaD3+DN5nXDRQ="
